interface WebIDL {
	void WebIDL();
	void WebIDL(long x);
	long getValueXByValue();
	[Value] WebIDL passThroughToValue(WebIDL i);

	WebIDL passThroughByPointer(WebIDL i);
	[Ref] WebIDL passThroughByReference([Ref] WebIDL i);
};